### ISSUE TITLE
tls: Keeping TLSv1 enabled for backwards compatibility

### ISSUE THREAD

**Issue by velitasali** [uprotocol/platform-java#4]
OpenJDK is now disabling TLSv1 and TLSv1.1 by default on its newer releases as those versions are considered insecure. 

Related: https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/

uprotocol uses TLSv1 to establish secure communication and migrating to TLSv1.2 would render it useless for some of the older versions of Android. Initially, I thought those versions would include Android 4.4 and below (as seen here https://support.globalsign.com/ssl/general-ssl/tls-protocol-compatibility), but people (on this thread https://stackoverflow.com/a/41466557) suggest that it can be enabled on Android 4.1.2 and after, and it is just disabled.

I would rather keep it enabled to support a greater range of devices, however, if it is going to affect only API 14 and API 15 (instead of all the way up to API 19), enabling v1.2 only won't hurt that much. 

What I am looking for is whether we can enable v1.0 and v1.1 without touching any local configurations. This post explains how to disable it: https://shashanksrivastava.medium.com/disable-tlsv1-tlsv1-1-in-java-8835d18fcfc0. I am wondering how we can re-enable in the pom file for instance. 

Also, I am unable to test older versions of Android with TLSv1.2 enabled right now, so it would be better if we kept the backward compatibility for now and maybe update it after it becomes clear those versions can work with TLSv1.2. 

Lastly, I know I can enable TLSv1 on my local machine, but this project uses CI, and I don't want other people to enable an insecure protocol for it. So, as I said, using the pom file or some project-level configuration would make better sense (which I haven't been able to find how). 

## edit

We are trying to enable it on a development machine as the change on OpenJDK doesn't affect Android.

**Comment by mubashir-rehman** [comment]
@MuntashirAkon Sorry to ping you. Can you please suggest some thing for this issue?

**Comment by velitasali** [comment]
I have just tested on an Android 4.2.2 device and haven't experienced any issue. So, I think increasing the min SDK version is the easiest option.
